# Numpy - Numerical Python

### Introduction to NumPy
## 1) What is NumPy?

NumPy is a Python library

It is used to work with numbers and arrays

It is faster than normal Python lists

### NumPy is mainly used in:

Data Analysis

Machine Learning

Image processing

## 2) Why NumPy is needed?

Python lists are slow

NumPy arrays are fast and memory-efficient

Easy to perform math operations

## Installing NumPy

(Only once)

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## Import NumPy

In [3]:
import numpy as np        ## np is just a short name

# (1) Introduction to Array

## 3) What is an Array?

- An array is a data structure that stores elements of the same data type in a continuous memory location.

In [4]:
arr = np.array([10, 20, 30, 40])

#### How this code matches the definition

arr → data structure (array)

[10, 20, 30, 40] → all are integers (same data type)

NumPy stores them in continuous memory

#### Access using index:

arr[0]   # 10

# (2) Creation & Printing of an Array

## Creating a 1D Array

A one-dimensional (1D) array is an array that stores elements in a single row.

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


## Creating a 2D Array

A two-dimensional (2D) array is an array that stores elements in rows and columns, similar to a table or matrix.

In [9]:
import numpy as np

arr2 = np.array([[1, 2], [3, 4]])
print(arr2)

[[1 2]
 [3 4]]


### Checking Array Type

In [10]:
type(arr)

numpy.ndarray

# (3) Basic Operations in NumPy

## i) Array Indexing

Array indexing is used to access a specific element of an array using its position number (index).

In [11]:
arr = np.array([10, 20, 30, 40])

print(arr[0])
print(arr[2])

10
30


## ii) Array Slicing

Array slicing is used to access a group of elements from an array.

In [12]:
print(arr[1:3])

[20 30]


## iii) Array Shape

Array shape shows the number of rows and columns in an array.

In [13]:
arr2 = np.array([[1, 2], [3, 4]])
print(arr2.shape)

(2, 2)


## iv) Array Size

Array size gives the total number of elements present in an array.

In [14]:
print(arr.size)

4


# Predefined / Special Array Creation Functions in NumPy
- Predefined array creation functions are built-in NumPy functions used to create arrays easily without manually entering values.

## i) np.zeros()
Creates an array filled with all zero values.

In [28]:
import numpy as np
np.zeros(4)

array([0., 0., 0., 0.])

## ii) np.ones()

Creates an array filled with all ones.

In [29]:
np.ones(4)

array([1., 1., 1., 1.])

## iii) np.eye()

Creates an identity matrix where diagonal elements are 1 and remaining elements are 0.

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## iv) np.arange()

Creates an array with values in a given range with a specific step size.

In [31]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

## V) np.linspace()

Creates an array with evenly spaced numbers between a given range.

In [32]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## vi) np.full()

Creates an array filled with a constant value.

In [35]:
np.full(4, 7)

array([7, 7, 7, 7])

## Vii) np.empty()

Creates an array without initializing values (contains garbage values).

In [38]:
np.empty(3)

array([1., 1., 1.])

## Viii) np.random.rand()

Creates an array of random values between 0 and 1.



In [39]:
np.random.rand(4)

array([0.55949113, 0.56283248, 0.33462746, 0.5005495 ])

## iX) np.random.randint()

Creates an array of random integers within a given range.

In [41]:
np.random.randint(1, 10, 5)

array([4, 5, 7, 2, 3])

# (4) Mathematical Functions of NumPy

## i) Sum

Sum adds all the elements in an array and gives the total value.

In [20]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(np.sum(arr))

10


## ii) Mean (Average)

Mean is the average of all elements in an array.

In [16]:
print(np.mean(arr))

2.5


## iii) Minimum & Maximum

- Minimum returns the smallest value from the array.
- Maximum returns the largest value from the array.

In [17]:
print(np.min(arr))
print(np.max(arr))

1
4


## iv) Square Root
- Square root returns the root value of each element in the array.

In [18]:
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.        ]


## V) Power
- Power raises each element in the array to the given exponent.

In [22]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(np.power(arr, 2))

[ 1  4  9 16]


# (5) NumPy With Images
- NumPy with images means treating an image as an array of numbers so that we can process and analyze images easily.
- Image = collection of pixels

- Pixel = number

- Image = 2D or 3D NumPy array

In [23]:
import numpy as np

# Each number represents a pixel value
image = np.array([
    [255, 200, 150],
    [100,  50,   0]
])

print(image)

[[255 200 150]
 [100  50   0]]


### Why NumPy is used with images

Fast processing

Easy pixel operations

Used in computer vision & ML

# (6) Advanced NumPy Functions

## a) Reshape
Reshape changes the shape of an array without changing its data.

In [24]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

## b) Flatten


Flatten converts a multi-dimensional array into a 1D array.

In [25]:
arr2 = np.array([[1, 2], [3, 4]])
arr2.flatten()

array([1, 2, 3, 4])

## c) Stack Arrays
Stacking means joining multiple NumPy arrays into a single array.

In [26]:
a = np.array([1, 2])
b = np.array([3, 4])
np.vstack((a, b))

array([[1, 2],
       [3, 4]])

## i) Vertical Stack (np.vstack)


- Vertical stacking joins arrays row-wise (one array on top of another).

In [42]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack((a, b))
print(result)

[[1 2 3]
 [4 5 6]]


## ii) Horizontal Stack (np.hstack)

- Horizontal stacking joins arrays column-wise (side by side).

In [43]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.hstack((a, b))
print(result)

[1 2 3 4 5 6]


## d) Broadcasting

Broadcasting allows NumPy to perform operations on arrays of different shapes.

In [27]:
arr = np.array([1, 2, 3])
arr + 5

array([6, 7, 8])

In [3]:
arr = np.array([[1,2,3],      # 2D array
                [4,5,6]])

print(arr + 5)

[[ 6  7  8]
 [ 9 10 11]]


# (7) NumPy Vectorization


#### - NumPy vectorization means performing operations on an entire array at once without using loops.

#### Why Vectorization is Used

Faster than loops

Less code

More readable

Optimized in NumPy

In [44]:
import numpy as np

arr = np.array([10, 20, 30, 40])
result = arr + 5

print(result)

[15 25 35 45]


### Explanation

5 is added to each element

No loop is written

Operation happens internally in C (fast)

### Vectorization vs Loops
❌ Using Loop

In [45]:
import numpy as np

arr = np.array([10, 20, 30, 40])
result = []

for i in arr:
    result.append(i + 5)

print(result)

[15, 25, 35, 45]


### ✅ Using Vectorization

In [46]:
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr + 5)

[15 25 35 45]


# Parallel Computing in NumPy
##### Parallel computing means doing multiple calculations at the same time instead of one by one.

#### NumPy internally uses:

C language

Multi-core CPU

SIMD (Single Instruction Multiple Data)

So even one NumPy line runs faster using parallelism.

In [2]:
import numpy as np

a = np.random.rand(1000000)
b = np.random.rand(1000000)

c = a + b   # runs in parallel internally
print(c)

[0.58439838 0.4399018  0.42967019 ... 1.33826274 0.66476529 0.66109739]


# View
####  A view is just another way to see the same array, so changing it also changes the original array.

In [4]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = a.view()

b[0] = 100

print(a)  # original array
print(b)  # view array

[100   2   3   4]
[100   2   3   4]


# Copy
##### A Copy creates a completely new array with its own memory.
##### So, changing the copy will NOT affect the original array.

In [5]:
import numpy as np

a = np.array([1, 2, 3, 4])
c = a.copy()

c[0] = 500

print(a)  # original array
print(c)  # copied array

[1 2 3 4]
[500   2   3   4]


# (8) Descriptive Statistics Using NumPy

#### Descriptive statistics means summarizing data using numbers so we can easily understand it.

## 1) Count
- Count tells how many values are present in the data.

In [6]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

count = len(data)

print("Data:", data)
print("Count:", count)

Data: [10 20 30 40 50]
Count: 5


## 2) Sum
- Sum means the total of all values.

In [7]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

total = np.sum(data)

print("Data:", data)
print("Sum:", total)

Data: [10 20 30 40 50]
Sum: 150


## 3) Mean (Average)

- Mean is the average value of the data.

In [8]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

mean = np.mean(data)

print("Data:", data)
print("Mean:", mean)

Data: [10 20 30 40 50]
Mean: 30.0


## 4) Median

- Median is the middle value when data is sorted.

In [9]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

median = np.median(data)

print("Data:", data)
print("Median:", median)

Data: [10 20 30 40 50]
Median: 30.0


## 5) Variance
- Variance shows how spread out the data is.

In [10]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

variance = np.var(data)

print("Data:", data)
print("Variance:", variance)

Data: [10 20 30 40 50]
Variance: 200.0


## 6) Standard Deviation

- Standard deviation shows how far values are from the mean.

In [11]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

std_dev = np.std(data)

print("Data:", data)
print("Standard Deviation:", std_dev)

Data: [10 20 30 40 50]
Standard Deviation: 14.142135623730951


## 7) Percentile

- Percentile shows the value below which a percentage of data lies.
- A percentile tells you the value below which a certain percent of the data falls.

#### Example in words:
- If the 50th percentile is 30, it means 50% of the values are less than or equal to 30.
- If I say 25th percentile, it means one-quarter of the numbers are below that value.
#### Percentile = position of a value in the data.

In [13]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

p50 = np.percentile(data, 50)

print("Data:", data)
print("50th Percentile:", p50)

Data: [10 20 30 40 50]
50th Percentile: 30.0


## 8) Covariance


- Covariance shows whether two variables move together.

In [14]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([2, 4, 6, 8])

covariance = np.cov(a, b)

print("Array A:", a)
print("Array B:", b)
print("Covariance Matrix:\n", covariance)

Array A: [1 2 3 4]
Array B: [2 4 6 8]
Covariance Matrix:
 [[1.66666667 3.33333333]
 [3.33333333 6.66666667]]


# Data Manipulation with Pandas

# What is Pandas?
- Pandas is a Python library that helps us work with data easily.
- It is mainly used to store, clean, analyze, and manipulate data in the form of tables (rows and columns), just like Excel or a database, but using Python.

## 2. Pandas vs NumPy

### NumPy

Used for numbers and mathematical calculations

Works mainly with arrays

Faster for calculations

### Pandas

Used for table data (rows & columns)

Works with Series and DataFrames

Easy for data analysis and cleaning

## 3. Why use Pandas over NumPy?

Pandas handles rows & columns with names

Easy to remove null values

Easy filtering, sorting, grouping

Best for real-world data (Excel, CSV, SQL)

### Use Pandas when working with datasets, not just numbers.

# (1) Series and DataFrames

## Series

- A Series is a one-dimensional data structure (like a single column).

In [15]:
import pandas as pd

s = pd.Series([10, 20, 30, 40])

print(s)

0    10
1    20
2    30
3    40
dtype: int64


## DataFrame

- A DataFrame is a two-dimensional table with rows and columns.

In [16]:
import pandas as pd

data = {
    "Name": ["A", "B", "C"],
    "Age": [20, 21, 22],
    "Marks": [80, 85, 90]
}

df = pd.DataFrame(data)

print(df)

  Name  Age  Marks
0    A   20     80
1    B   21     85
2    C   22     90


# (2) Data Importing and Exporting through Excel, CSV Files

## Import CSV File

Used to read data from a CSV file into Pandas.

In [23]:
import pandas as pd

df = pd.read_csv("loandata.csv")

print(df)

      Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001722    Male     Yes          0      Graduate            No   
1    LP002502  Female     Yes          2  Not Graduate           NaN   
2    LP002949  Female      No         3+      Graduate           NaN   
3    LP002603  Female      No          0      Graduate            No   
4    LP001644     NaN     Yes          0      Graduate           Yes   
..        ...     ...     ...        ...           ...           ...   
609  LP001640    Male     Yes          0      Graduate           Yes   
610  LP001536    Male     Yes         3+      Graduate            No   
611  LP001585     NaN     Yes         3+      Graduate            No   
612  LP002101    Male     Yes          0      Graduate           NaN   
613  LP002317    Male     Yes         3+      Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0                150             1800.0       135.0           

## Import Excel File

In [ ]:
import pandas as pd

df = pd.read_excel("data.xlsx")

print(df)

## Export to CSV
- to_csv() is a Pandas function used to save a DataFrame into a CSV (Comma-Separated Values) file, so the data can be easily shared, stored, or opened in tools like Excel.

In [27]:
import pandas as pd

# Create or read data
df = pd.read_csv("loandata.csv")   # use your file name/path

# Export to CSV
df.to_csv("output.csv", index=False)

print("Data exported to output.csv successfully")

Data exported to output.csv successfully


## Export to Excel
- to_excel() is a Pandas function used to save a DataFrame into an Excel (.xlsx) file, keeping the data in a spreadsheet format that is easy to read and use.

In [ ]:
import pandas as pd

# Create or read data
df = pd.read_csv("data.csv")   # use your file name/path

# Export to Excel
df.to_excel("output.xlsx", index=False)

print("Data exported to output.xlsx successfully")

# (3) Data Understanding Operations

## 1. head()

Shows the first few rows of the dataset so we can quickly see how the data looks.

In [28]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y
2,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y
4,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y


In [30]:
df.head(2)   # shows first 2 rows

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y


## 2. tail()

Shows the last few rows of the dataset.

In [31]:
df.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
609,LP001640,Male,Yes,0,Graduate,Yes,39147,4750.0,120.0,360.0,1.0,Semiurban,Y
610,LP001536,Male,Yes,3+,Graduate,No,39999,0.0,600.0,180.0,0.0,Semiurban,Y
611,LP001585,NaN,Yes,3+,Graduate,No,51763,0.0,700.0,300.0,1.0,Urban,Y
612,LP002101,Male,Yes,0,Graduate,NaN,63337,0.0,490.0,180.0,1.0,Urban,Y
613,LP002317,Male,Yes,3+,Graduate,No,81000,0.0,360.0,360.0,0.0,Rural,N


## 3. shape


Shows how many rows and columns are present in the dataset.

In [32]:
df.shape

(614, 13)

## 4. columns

Shows all column names in the dataset.

In [33]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

## 5. dtypes

Shows the data type of each column (int, float, object, etc.).

In [34]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

## 6. info()

#### Gives a complete summary of the dataset including:

Number of rows

Column names

Data types

Non-null values

Memory usage

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


## 7. describe()

- Gives a statistical summary of numeric columns.

##### It shows:

count

mean

standard deviation

minimum

maximum

25%, 50%, 75% (quartiles)

In [36]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000


In [38]:
df.describe(include="all")   # includes categorical columns also

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
count,614,601,611,599,614,582,614.000000,614.000000,592.000000,600.00000,564.000000,614,614
unique,614,2,2,4,2,2,NaN,NaN,NaN,NaN,NaN,3,2
top,LP001722,Male,Yes,0,Graduate,No,NaN,NaN,NaN,NaN,NaN,Semiurban,Y
freq,1,489,398,345,480,500,NaN,NaN,NaN,NaN,NaN,233,422
mean,NaN,NaN,NaN,NaN,NaN,NaN,5403.459283,1621.245798,146.412162,342.00000,0.842199,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,6109.041673,2926.248369,85.587325,65.12041,0.364878,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,150.000000,0.000000,9.000000,12.00000,0.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,2877.500000,0.000000,100.000000,360.00000,1.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,3812.500000,1188.500000,128.000000,360.00000,1.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,5795.000000,2297.250000,168.000000,360.00000,1.000000,NaN,NaN


# (4) Indexing and slicing and More filtering with Conditional Slicing

### 1. INDEXING

Indexing means selecting specific data (row or column) from the dataset.

### 1.1 Column Indexing (Single Column)
- Selects only LoanAmount column

In [40]:
df["LoanAmount"]

0      135.0
1       98.0
2      350.0
3      113.0
4      168.0
       ...  
609    120.0
610    600.0
611    700.0
612    490.0
613    360.0
Name: LoanAmount, Length: 614, dtype: float64

### 1.2 Column Indexing (Multiple Columns)
- Selects multiple columns

In [41]:
df[["ApplicantIncome", "LoanAmount", "Loan_Status"]]

,ApplicantIncome,LoanAmount,Loan_Status
0,150,135.0,N
1,210,98.0,Y
2,416,350.0,N
3,645,113.0,Y
4,674,168.0,Y
...,...,...,...
609,39147,120.0,Y
610,39999,600.0,Y
611,51763,700.0,Y
612,63337,490.0,Y


# WHAT IS loc ?
#### loc → LABEL-BASED SELECTION

- loc is used to select rows and columns using their NAMES (labels).

## 1. Get first row
- Gets row with index label 0

In [42]:
df.loc[0]

Loan_ID              LP001722
Gender                   Male
Married                   Yes
Dependents                  0
Education            Graduate
Self_Employed              No
ApplicantIncome           150
CoapplicantIncome      1800.0
LoanAmount              135.0
Loan_Amount_Term        360.0
Credit_History            1.0
Property_Area           Rural
Loan_Status                 N
Name: 0, dtype: object

## 2. Get first 5 rows
- Includes both 0 and 4

In [43]:
df.loc[0:4]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y
2,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y
4,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y


## 3. Get specific columns
- : means all rows

In [44]:
df.loc[:, ["LoanAmount", "Loan_Status"]]

,LoanAmount,Loan_Status
0,135.0,N
1,98.0,Y
2,350.0,N
3,113.0,Y
4,168.0,Y
...,...,...
609,120.0,Y
610,600.0,Y
611,700.0,Y
612,490.0,Y


## 4. Get specific rows & columns

In [45]:
df.loc[0:5, ["Gender", "Education", "Loan_Status"]]

,Gender,Education,Loan_Status
0,Male,Graduate,N
1,Female,Not Graduate,Y
2,Female,Graduate,N
3,Female,Graduate,Y
4,NaN,Graduate,Y
5,Male,Graduate,N


# WHAT IS iloc ?
iloc → POSITION-BASED SELECTION

#### iloc is used to select rows and columns using position numbers.

### 1. Get first row

In [46]:
df.iloc[0]

Loan_ID              LP001722
Gender                   Male
Married                   Yes
Dependents                  0
Education            Graduate
Self_Employed              No
ApplicantIncome           150
CoapplicantIncome      1800.0
LoanAmount              135.0
Loan_Amount_Term        360.0
Credit_History            1.0
Property_Area           Rural
Loan_Status                 N
Name: 0, dtype: object

### 2. Get first 5 rows
- End value is NOT included

In [47]:
df.iloc[0:5]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y
2,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y
4,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y


### 3. Get columns by position
Columns:

6 → ApplicantIncome

7 → CoapplicantIncome

8 → LoanAmount

In [48]:
df.iloc[:, 6:9]

,ApplicantIncome,CoapplicantIncome,LoanAmount
0,150,1800.0,135.0
1,210,2917.0,98.0
2,416,41667.0,350.0
3,645,3683.0,113.0
4,674,5296.0,168.0
...,...,...,...
609,39147,4750.0,120.0
610,39999,0.0,600.0
611,51763,0.0,700.0
612,63337,0.0,490.0


### 4. Get specific rows & columns

In [49]:
df.iloc[0:5, 6:10]

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term
0,150,1800.0,135.0,360.0
1,210,2917.0,98.0,360.0
2,416,41667.0,350.0,180.0
3,645,3683.0,113.0,480.0
4,674,5296.0,168.0,360.0


# 1.Conditional Filtering
Select rows that satisfy a single condition.

In [50]:
df[df["Loan_Status"] == "Y"]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y
4,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y
6,LP002345,Male,Yes,0,Graduate,No,1025,2773.0,112.0,360.0,1.0,Rural,Y
7,LP002717,Male,Yes,0,Graduate,No,1025,5500.0,216.0,360.0,NaN,Rural,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
608,LP002422,Male,No,1,Graduate,No,37719,0.0,152.0,360.0,1.0,Semiurban,Y
609,LP001640,Male,Yes,0,Graduate,Yes,39147,4750.0,120.0,360.0,1.0,Semiurban,Y
610,LP001536,Male,Yes,3+,Graduate,No,39999,0.0,600.0,180.0,0.0,Semiurban,Y
611,LP001585,NaN,Yes,3+,Graduate,No,51763,0.0,700.0,300.0,1.0,Urban,Y


## 2. Filtering Numeric Columns
- Filter rows based on numeric comparison.

In [51]:
df[df["ApplicantIncome"] > 5000]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
423,LP001497,Male,Yes,2,Graduate,No,5042,2083.0,185.0,360.0,1.0,Rural,N
424,LP001398,Male,No,0,Graduate,NaN,5050,0.0,118.0,360.0,1.0,Semiurban,Y
425,LP002847,Male,Yes,NaN,Graduate,No,5116,1451.0,165.0,360.0,0.0,Urban,N
426,LP002188,Male,No,0,Graduate,No,5124,0.0,124.0,NaN,0.0,Rural,N
427,LP001872,Male,No,0,Graduate,Yes,5166,0.0,128.0,360.0,1.0,Semiurban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP001640,Male,Yes,0,Graduate,Yes,39147,4750.0,120.0,360.0,1.0,Semiurban,Y
610,LP001536,Male,Yes,3+,Graduate,No,39999,0.0,600.0,180.0,0.0,Semiurban,Y
611,LP001585,NaN,Yes,3+,Graduate,No,51763,0.0,700.0,300.0,1.0,Urban,Y
612,LP002101,Male,Yes,0,Graduate,NaN,63337,0.0,490.0,180.0,1.0,Urban,Y


## 3. Filtering Using AND Condition (&)
- Select rows where all conditions are true.

In [52]:
df[(df["ApplicantIncome"] > 5000) & (df["Loan_Status"] == "Y")]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
424,LP001398,Male,No,0,Graduate,NaN,5050,0.0,118.0,360.0,1.0,Semiurban,Y
427,LP001872,Male,No,0,Graduate,Yes,5166,0.0,128.0,360.0,1.0,Semiurban,Y
428,LP002160,Male,Yes,3+,Graduate,No,5167,3167.0,200.0,360.0,1.0,Semiurban,Y
429,LP002197,Male,Yes,2,Graduate,No,5185,0.0,155.0,360.0,1.0,Semiurban,Y
430,LP002489,Female,No,1,Not Graduate,NaN,5191,0.0,132.0,360.0,1.0,Semiurban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
608,LP002422,Male,No,1,Graduate,No,37719,0.0,152.0,360.0,1.0,Semiurban,Y
609,LP001640,Male,Yes,0,Graduate,Yes,39147,4750.0,120.0,360.0,1.0,Semiurban,Y
610,LP001536,Male,Yes,3+,Graduate,No,39999,0.0,600.0,180.0,0.0,Semiurban,Y
611,LP001585,NaN,Yes,3+,Graduate,No,51763,0.0,700.0,300.0,1.0,Urban,Y


## 4. Filtering Using OR Condition (|)

Select rows where any one condition is true.

In [53]:
df[(df["Education"] == "Graduate") | (df["Property_Area"] == "Urban")]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N
2,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y
4,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y
5,LP001259,Male,Yes,1,Graduate,Yes,1000,3022.0,110.0,360.0,1.0,Urban,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP001640,Male,Yes,0,Graduate,Yes,39147,4750.0,120.0,360.0,1.0,Semiurban,Y
610,LP001536,Male,Yes,3+,Graduate,No,39999,0.0,600.0,180.0,0.0,Semiurban,Y
611,LP001585,NaN,Yes,3+,Graduate,No,51763,0.0,700.0,300.0,1.0,Urban,Y
612,LP002101,Male,Yes,0,Graduate,NaN,63337,0.0,490.0,180.0,1.0,Urban,Y


## 5. Filtering Using NOT Condition (~)


- It is used to select all rows that do NOT satisfy a given condition, meaning it removes the rows that match the condition and keeps the rest..

In [54]:
df[~(df["Self_Employed"] == "Yes")]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y
2,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y
6,LP002345,Male,Yes,0,Graduate,No,1025,2773.0,112.0,360.0,1.0,Rural,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
608,LP002422,Male,No,1,Graduate,No,37719,0.0,152.0,360.0,1.0,Semiurban,Y
610,LP001536,Male,Yes,3+,Graduate,No,39999,0.0,600.0,180.0,0.0,Semiurban,Y
611,LP001585,NaN,Yes,3+,Graduate,No,51763,0.0,700.0,300.0,1.0,Urban,Y
612,LP002101,Male,Yes,0,Graduate,NaN,63337,0.0,490.0,180.0,1.0,Urban,Y


## 6. Filtering Missing Values (isnull())

Select rows that contain missing values.

In [55]:
df[df["LoanAmount"].isnull()]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
25,LP002113,Female,No,3+,Not Graduate,No,1830,0.0,NaN,360.0,0.0,Urban,N
40,LP001990,Male,No,0,Not Graduate,No,2000,0.0,NaN,360.0,1.0,Urban,N
60,LP002401,Male,Yes,0,Graduate,No,2213,1125.0,NaN,360.0,1.0,Urban,Y
66,LP001106,Male,Yes,0,Graduate,No,2275,2067.0,NaN,360.0,1.0,Urban,Y
81,LP001266,Male,Yes,1,Graduate,Yes,2395,0.0,NaN,360.0,1.0,Semiurban,Y
85,LP002960,Male,Yes,0,Not Graduate,No,2400,3800.0,NaN,180.0,1.0,Urban,N
97,LP002784,Male,Yes,1,Not Graduate,No,2492,2375.0,NaN,360.0,1.0,Rural,Y
166,LP002533,Male,Yes,2,Graduate,No,2947,1603.0,NaN,360.0,1.0,Urban,N
177,LP002243,Male,Yes,0,Not Graduate,No,3010,3136.0,NaN,360.0,0.0,Urban,N
278,LP002054,Male,Yes,2,Not Graduate,No,3601,1590.0,NaN,360.0,1.0,Rural,Y


## 7.  Filtering Non-Missing Values (notnull())

Select rows that do not contain missing values.

In [56]:
df[df["Credit_History"].notnull()]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y
4,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y
5,LP001259,Male,Yes,1,Graduate,Yes,1000,3022.0,110.0,360.0,1.0,Urban,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP001640,Male,Yes,0,Graduate,Yes,39147,4750.0,120.0,360.0,1.0,Semiurban,Y
610,LP001536,Male,Yes,3+,Graduate,No,39999,0.0,600.0,180.0,0.0,Semiurban,Y
611,LP001585,NaN,Yes,3+,Graduate,No,51763,0.0,700.0,300.0,1.0,Urban,Y
612,LP002101,Male,Yes,0,Graduate,NaN,63337,0.0,490.0,180.0,1.0,Urban,Y


## 8.  Filtering Using loc with Condition

Filter rows and select specific columns together.
- From the data, take only approved loans and display income and loan amount.

In [57]:
df.loc[df["Loan_Status"] == "Y", ["ApplicantIncome", "LoanAmount"]]

,ApplicantIncome,LoanAmount
1,210,98.0
3,645,113.0
4,674,168.0
6,1025,112.0
7,1025,216.0
...,...,...
608,37719,152.0
609,39147,120.0
610,39999,600.0
611,51763,700.0


# (5) Groupby, Pivot table and Cross Tab

## 1. GROUPBY
### What is GroupBy?
- GroupBy is used to group data based on a column and apply calculations like sum, mean, count.

### 1.1 GroupBy with Mean

In [59]:
df.groupby("Loan_Status")["ApplicantIncome"].mean()  # groups data by Loan_Status and finds average income

Loan_Status
N    5446.078125
Y    5384.068720
Name: ApplicantIncome, dtype: float64

In [60]:
df.groupby("Gender")["LoanAmount"].mean()

Gender
Female    126.697248
Male      149.265957
Name: LoanAmount, dtype: float64

### 1.2 GroupBy with Count

In [61]:
df.groupby("Gender")["Loan_ID"].count()  # counts number of loans for each gender

Gender
Female    112
Male      489
Name: Loan_ID, dtype: int64

### 1.3 GroupBy with Multiple Columns

In [62]:
df.groupby(["Gender", "Loan_Status"])["LoanAmount"].mean()  # groups by gender and loan status, then finds average loan amount

Gender  Loan_Status
Female  N              128.694444
        Y              125.712329
Male    N              157.878571
        Y              145.612121
Name: LoanAmount, dtype: float64

### 1.4 Multiple Aggregations

In [64]:
df.groupby("Property_Area")["LoanAmount"].agg(["mean", "sum", "count"])  # calculates mean, sum and count together

,mean,sum,count
Property_Area,,,
Rural,152.260116,26341.0,173
Semiurban,145.504386,33175.0,228
Urban,142.198953,27160.0,191


# 2. PIVOT TABLE
### What is Pivot Table?
- A pivot table is a method used to organize, group, and summarize large amounts of data into a simple table, so we can easily compare values and understand the data.

## 2.1 Simple Pivot Table

In [65]:
pd.pivot_table(
    df,                                # dataset
    values="LoanAmount",               # values to calculate
    index="Loan_Status",               # rows
    aggfunc="mean"                     # calculation
)

,LoanAmount
Loan_Status,
N,151.220994
Y,144.294404


### 2.2 Pivot Table with Rows & Columns
- It groups the data by Gender (rows) and Loan_Status (columns) and shows the average LoanAmount in a table.
- Show average loan amount for each gender, separately for approved and not approved loans.

In [66]:
pd.pivot_table(
    df,                                # dataset
    values="LoanAmount",               # value column
    index="Gender",                    # rows
    columns="Loan_Status",             # columns
    aggfunc="mean"                     # aggregation
)

Loan_Status,N,Y
Gender,,
Female,128.694444,125.712329
Male,157.878571,145.612121


### 2.3 Pivot Table with Multiple Functions
- It is used to summarize the same column using more than one calculation (like mean, max, count) at the same time, grouped by a category.

In [67]:
pd.pivot_table(
    df,
    values="ApplicantIncome",
    index="Education",
    aggfunc=["mean", "max", "count"]
)

,mean,max,count
,ApplicantIncome,ApplicantIncome,ApplicantIncome
Education,,,
Graduate,5857.433333,81000,480
Not Graduate,3777.283582,18165,134


# 3. CROSS TAB (CROSSTAB)
### What is Crosstab
- A crosstab shows how many times each combination of two categories appears in the data.

### 3.1 Simple Crosstab
- Count how many males and females got loan approved and not approved

In [68]:
pd.crosstab(df["Gender"], df["Loan_Status"])  

Loan_Status,N,Y
Gender,,
Female,37,75
Male,150,339


### 3.2 Crosstab with Normalization
### i) normalize=True 
- Show loan approval percentages for each property area.
#### normalize=True → percentages, not counts

### Memory Trick 

normalize=True → overall percentages

normalize="index" → row-wise percentages

normalize="columns" → column-wise percentages

In [69]:
pd.crosstab(df["Property_Area"], df["Loan_Status"], normalize=True)  # shows percentage instead of count

Loan_Status,N,Y
Property_Area,,
Rural,0.112378,0.179153
Semiurban,0.087948,0.291531
Urban,0.112378,0.216612


In [71]:
pd.crosstab(df["Gender"], df["Loan_Status"], normalize=True)
# percentage out of total records

Loan_Status,N,Y
Gender,,
Female,0.061564,0.124792
Male,0.249584,0.564060


### ii). normalize="index" (ROW-WISE)
- It shows percentages inside each row, meaning for each gender, how many got loan approved and not approved.

In [72]:
pd.crosstab(df["Gender"], df["Loan_Status"], normalize="index")
# shows loan approval % for each gender

Loan_Status,N,Y
Gender,,
Female,0.330357,0.669643
Male,0.306748,0.693252


### iii). normalize="columns" (COLUMN-WISE)
- It shows percentages inside each column, meaning for approved and not approved loans, how many are male and female.

In [73]:
pd.crosstab(df["Gender"], df["Loan_Status"], normalize="columns")  # shows gender distribution within each loan status


Loan_Status,N,Y
Gender,,
Female,0.197861,0.181159
Male,0.802139,0.818841


# (6) Concatenating and Merging Joining

### 1.1 Concatenation (concat)

- Concatenation means combining DataFrames either row-wise or column-wise.

### i) Row-wise Concatenation
- Row-wise concatenation is used to combine data from multiple tables with the same columns into one table

In [76]:
df_row = pd.concat([df, df])
print(df_row)

      Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001722    Male     Yes          0      Graduate            No   
1    LP002502  Female     Yes          2  Not Graduate           NaN   
2    LP002949  Female      No         3+      Graduate           NaN   
3    LP002603  Female      No          0      Graduate            No   
4    LP001644     NaN     Yes          0      Graduate           Yes   
..        ...     ...     ...        ...           ...           ...   
609  LP001640    Male     Yes          0      Graduate           Yes   
610  LP001536    Male     Yes         3+      Graduate            No   
611  LP001585     NaN     Yes         3+      Graduate            No   
612  LP002101    Male     Yes          0      Graduate           NaN   
613  LP002317    Male     Yes         3+      Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0                150             1800.0       135.0           

In [77]:
df_row.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y
2,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y
4,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y


### ii) Column-wise Concatenation
- Put ApplicantIncome and LoanAmount columns next to each other in one table.
- axis=1 means add as columns, not rows

In [78]:
df_col = pd.concat([df[["ApplicantIncome"]], df[["LoanAmount"]]], axis=1)
print(df_col)

     ApplicantIncome  LoanAmount
0                150       135.0
1                210        98.0
2                416       350.0
3                645       113.0
4                674       168.0
..               ...         ...
609            39147       120.0
610            39999       600.0
611            51763       700.0
612            63337       490.0
613            81000       360.0

[614 rows x 2 columns]


### 1.2 Merging / Joining (merge)
- Merging means connecting two tables using one common column so related data comes together in one table.

### Create second DataFrame (example)
- Create a new table with only Loan_ID and Property_Area columns from the original data.

In [80]:
df_extra = df[["Loan_ID", "Property_Area"]]
print(df_extra)

      Loan_ID Property_Area
0    LP001722         Rural
1    LP002502     Semiurban
2    LP002949         Urban
3    LP002603         Rural
4    LP001644         Rural
..        ...           ...
609  LP001640     Semiurban
610  LP001536     Semiurban
611  LP001585         Urban
612  LP002101         Urban
613  LP002317         Rural

[614 rows x 2 columns]


## 1) Inner Join
- Keeps only the rows that match in both tables.
#### The "how" parameter is used to decide which rows should be kept when two tables are merged.

In [81]:
pd.merge(df, df_extra, on="Loan_ID", how="inner")

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area_x,Loan_Status,Property_Area_y
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N,Rural
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y,Semiurban
2,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N,Urban
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y,Rural
4,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y,Rural
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP001640,Male,Yes,0,Graduate,Yes,39147,4750.0,120.0,360.0,1.0,Semiurban,Y,Semiurban
610,LP001536,Male,Yes,3+,Graduate,No,39999,0.0,600.0,180.0,0.0,Semiurban,Y,Semiurban
611,LP001585,NaN,Yes,3+,Graduate,No,51763,0.0,700.0,300.0,1.0,Urban,Y,Urban
612,LP002101,Male,Yes,0,Graduate,NaN,63337,0.0,490.0,180.0,1.0,Urban,Y,Urban


### 2) Left Join
Keeps all rows from the left table and only matching rows from the right table.

In [82]:
pd.merge(df, df_extra, on="Loan_ID", how="left")

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area_x,Loan_Status,Property_Area_y
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N,Rural
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y,Semiurban
2,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N,Urban
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y,Rural
4,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y,Rural
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP001640,Male,Yes,0,Graduate,Yes,39147,4750.0,120.0,360.0,1.0,Semiurban,Y,Semiurban
610,LP001536,Male,Yes,3+,Graduate,No,39999,0.0,600.0,180.0,0.0,Semiurban,Y,Semiurban
611,LP001585,NaN,Yes,3+,Graduate,No,51763,0.0,700.0,300.0,1.0,Urban,Y,Urban
612,LP002101,Male,Yes,0,Graduate,NaN,63337,0.0,490.0,180.0,1.0,Urban,Y,Urban


### 3) Right Join
- Keeps all rows from the right table and only matching rows from the left table.

In [83]:
pd.merge(df, df_extra, on="Loan_ID", how="right")

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area_x,Loan_Status,Property_Area_y
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N,Rural
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y,Semiurban
2,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N,Urban
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y,Rural
4,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y,Rural
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP001640,Male,Yes,0,Graduate,Yes,39147,4750.0,120.0,360.0,1.0,Semiurban,Y,Semiurban
610,LP001536,Male,Yes,3+,Graduate,No,39999,0.0,600.0,180.0,0.0,Semiurban,Y,Semiurban
611,LP001585,NaN,Yes,3+,Graduate,No,51763,0.0,700.0,300.0,1.0,Urban,Y,Urban
612,LP002101,Male,Yes,0,Graduate,NaN,63337,0.0,490.0,180.0,1.0,Urban,Y,Urban


### 4) Outer Join
- Keeps all rows from both tables, whether they match or not.

In [84]:
pd.merge(df, df_extra, on="Loan_ID", how="outer")

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area_x,Loan_Status,Property_Area_y
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y,Urban
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,Rural
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,Urban
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,Urban
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y,Rural
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,Rural
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y,Urban
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y,Urban


# (7) Descriptive Statistics
- Descriptive statistics summarize numeric data using values like mean, min, max, etc.

### 1) describe()
- Shows a quick summary of numbers like count, average, min, max, and spread.

In [85]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000


### 2) Mean (Average)
- Gives the average value of the column.

In [86]:
df["ApplicantIncome"].mean()

5403.459283387622

### 3) Median
- Gives the middle value of the data.

In [87]:
df["LoanAmount"].median()

128.0

## 4) Mode
- Gives the value that appears most times.

In [88]:
df["Property_Area"].mode()

0    Semiurban
Name: Property_Area, dtype: object

### 5) Minimum & Maximum
- Gives the smallest value.
- Gives the largest value.

In [89]:
df["LoanAmount"].min()
df["LoanAmount"].max()

700.0

### 6) Standard Deviation
- It tells how far the numbers usually are from the average.
- Small value → numbers are close together
- Big value → numbers are far apart

In [90]:
df["ApplicantIncome"].std()

6109.041673387178

### 7) Variance
- It tells how much the numbers are spread out from each other.
- Small variance → numbers are similar
- Big variance → numbers are very different

In [91]:
df["ApplicantIncome"].var()

37320390.167181216

### 8) Sum

In [92]:
df["ApplicantIncome"].sum()

3317724

### 9) count

In [94]:
df["LoanAmount"].count()

592

### 10) Value Counts (Categorical Data)
- Shows how many times each value appears.

In [95]:
df["Loan_Status"].value_counts()

Loan_Status
Y    422
N    192
Name: count, dtype: int64

# (8) REMOVING DUPLICATES
- Duplicate rows are the same data repeated more than once in the dataset.

### 8.1) Check Duplicate Rows
- Checks which rows are repeated and marks them as True or False.

In [96]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
609    False
610    False
611    False
612    False
613    False
Length: 614, dtype: bool

### 8.2) Count Duplicates
- Counts how many duplicate rows are present in the dataset.

In [97]:
df.duplicated().sum()

0

### 8.3) Remove Duplicate Rows
- Removes all repeated rows and keeps only unique rows.

In [98]:
df_no_dup = df.drop_duplicates()

### 8.4) Remove Duplicates Based on Column
- Removes duplicates based only on the Loan_ID column.

In [99]:
df.drop_duplicates(subset=["Loan_ID"])

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y
2,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y
4,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP001640,Male,Yes,0,Graduate,Yes,39147,4750.0,120.0,360.0,1.0,Semiurban,Y
610,LP001536,Male,Yes,3+,Graduate,No,39999,0.0,600.0,180.0,0.0,Semiurban,Y
611,LP001585,NaN,Yes,3+,Graduate,No,51763,0.0,700.0,300.0,1.0,Urban,Y
612,LP002101,Male,Yes,0,Graduate,NaN,63337,0.0,490.0,180.0,1.0,Urban,Y


### 8.5) Keep Last Duplicate
- Removes duplicates but keeps the last occurrence of each duplicate.

In [100]:
df.drop_duplicates(subset=["Loan_ID"], keep="last")

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y
2,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y
4,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP001640,Male,Yes,0,Graduate,Yes,39147,4750.0,120.0,360.0,1.0,Semiurban,Y
610,LP001536,Male,Yes,3+,Graduate,No,39999,0.0,600.0,180.0,0.0,Semiurban,Y
611,LP001585,NaN,Yes,3+,Graduate,No,51763,0.0,700.0,300.0,1.0,Urban,Y
612,LP002101,Male,Yes,0,Graduate,NaN,63337,0.0,490.0,180.0,1.0,Urban,Y


### 8.6) Remove Duplicates In-place
- Removes duplicates directly from the original dataset.

In [101]:
df.drop_duplicates(inplace=True)

# (9) String Manipulation

#### String operations in Pandas are done using .str

- Column.str.function()

### 1. Convert to Lowercase

Converts all text into small letters.

In [102]:
df["Property_Area"].str.lower()

0          rural
1      semiurban
2          urban
3          rural
4          rural
         ...    
609    semiurban
610    semiurban
611        urban
612        urban
613        rural
Name: Property_Area, Length: 614, dtype: object

### 2. Convert to Uppercase


Converts all text into capital letters.

In [103]:
df["Property_Area"].str.upper()

0          RURAL
1      SEMIURBAN
2          URBAN
3          RURAL
4          RURAL
         ...    
609    SEMIURBAN
610    SEMIURBAN
611        URBAN
612        URBAN
613        RURAL
Name: Property_Area, Length: 614, dtype: object

### 3. Capitalize First Letter
Makes only the first letter capital.

In [104]:
df["Education"].str.capitalize()

0          Graduate
1      Not graduate
2          Graduate
3          Graduate
4          Graduate
           ...     
609        Graduate
610        Graduate
611        Graduate
612        Graduate
613        Graduate
Name: Education, Length: 614, dtype: object

### 4. Remove Extra Spaces (strip)
Removes spaces from start and end of text.

In [105]:
df["Gender"].str.strip()

0        Male
1      Female
2      Female
3      Female
4         NaN
        ...  
609      Male
610      Male
611       NaN
612      Male
613      Male
Name: Gender, Length: 614, dtype: object

### 5. Remove Left Spaces (lstrip)

In [106]:
df["Gender"].str.lstrip()

0        Male
1      Female
2      Female
3      Female
4         NaN
        ...  
609      Male
610      Male
611       NaN
612      Male
613      Male
Name: Gender, Length: 614, dtype: object

### 6. Remove Right Spaces (rstrip)

In [107]:
df["Gender"].str.rstrip()

0        Male
1      Female
2      Female
3      Female
4         NaN
        ...  
609      Male
610      Male
611       NaN
612      Male
613      Male
Name: Gender, Length: 614, dtype: object

### 7.Replace Text (replace)


Replaces one string with another.

In [108]:
df["Gender"].str.replace("Male", "M")

0           M
1      Female
2      Female
3      Female
4         NaN
        ...  
609         M
610         M
611       NaN
612         M
613         M
Name: Gender, Length: 614, dtype: object

### 8. Check String Contains (contains)

Checks if a string contains a specific word or letter.

In [109]:
df[df["Loan_ID"].str.contains("LP")]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y
2,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y
4,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP001640,Male,Yes,0,Graduate,Yes,39147,4750.0,120.0,360.0,1.0,Semiurban,Y
610,LP001536,Male,Yes,3+,Graduate,No,39999,0.0,600.0,180.0,0.0,Semiurban,Y
611,LP001585,NaN,Yes,3+,Graduate,No,51763,0.0,700.0,300.0,1.0,Urban,Y
612,LP002101,Male,Yes,0,Graduate,NaN,63337,0.0,490.0,180.0,1.0,Urban,Y


### 9. Starts With (startswith)

Checks if string starts with given text.

In [110]:
df[df["Loan_ID"].str.startswith("LP")]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,N
1,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y
2,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
3,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,Y
4,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP001640,Male,Yes,0,Graduate,Yes,39147,4750.0,120.0,360.0,1.0,Semiurban,Y
610,LP001536,Male,Yes,3+,Graduate,No,39999,0.0,600.0,180.0,0.0,Semiurban,Y
611,LP001585,NaN,Yes,3+,Graduate,No,51763,0.0,700.0,300.0,1.0,Urban,Y
612,LP002101,Male,Yes,0,Graduate,NaN,63337,0.0,490.0,180.0,1.0,Urban,Y


### 10. Ends With (endswith)


Checks if string ends with given text.

In [111]:
df[df["Loan_ID"].str.endswith("1")]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
22,LP001581,Male,Yes,0,Not Graduate,NaN,1820,1769.0,95.0,360.0,1.0,Rural,Y
23,LP002361,Male,Yes,0,Graduate,No,1820,1719.0,100.0,360.0,1.0,Urban,Y
52,LP001431,Female,No,0,Graduate,No,2137,8980.0,137.0,360.0,0.0,Semiurban,Y
57,LP001641,Male,Yes,1,Graduate,Yes,2178,0.0,66.0,300.0,0.0,Rural,N
60,LP002401,Male,Yes,0,Graduate,No,2213,1125.0,NaN,360.0,1.0,Urban,Y
84,LP002051,Male,Yes,0,Graduate,No,2400,2167.0,115.0,360.0,1.0,Semiurban,Y
114,LP001841,Male,No,0,Not Graduate,Yes,2583,2167.0,104.0,360.0,1.0,Rural,Y
117,LP001041,Male,Yes,0,Graduate,NaN,2600,3500.0,115.0,NaN,1.0,Urban,Y
121,LP002341,Female,No,1,Graduate,No,2600,0.0,160.0,360.0,1.0,Urban,N
130,LP002141,Male,Yes,3+,Graduate,No,2666,2083.0,95.0,360.0,1.0,Rural,Y


### 11. String Length (len)
Gives length of each string.

In [112]:
df["Loan_ID"].str.len()

0      8
1      8
2      8
3      8
4      8
      ..
609    8
610    8
611    8
612    8
613    8
Name: Loan_ID, Length: 614, dtype: int64

### 12. Split String (split)

Splits a string into multiple parts.

In [113]:
df["Loan_ID"].str.split("_")

0      [LP001722]
1      [LP002502]
2      [LP002949]
3      [LP002603]
4      [LP001644]
          ...    
609    [LP001640]
610    [LP001536]
611    [LP001585]
612    [LP002101]
613    [LP002317]
Name: Loan_ID, Length: 614, dtype: object

### 13. Split and Access Part

In [114]:
df["Loan_ID"].str.split("_").str[0]

0      LP001722
1      LP002502
2      LP002949
3      LP002603
4      LP001644
         ...   
609    LP001640
610    LP001536
611    LP001585
612    LP002101
613    LP002317
Name: Loan_ID, Length: 614, dtype: object

### 14. Join Strings (cat)

Joins two string columns together.

In [115]:
df["Gender"].str.cat(df["Married"], sep="_")

0        Male_Yes
1      Female_Yes
2       Female_No
3       Female_No
4             NaN
          ...    
609      Male_Yes
610      Male_Yes
611           NaN
612      Male_Yes
613      Male_Yes
Name: Gender, Length: 614, dtype: object

### 15 Check String is Alphabet (isalpha)

In [116]:
df["Gender"].str.isalpha()

0      True
1      True
2      True
3      True
4       NaN
       ... 
609    True
610    True
611     NaN
612    True
613    True
Name: Gender, Length: 614, dtype: object

### 16. Check String is Numeric (isnumeric)

In [117]:
df["Loan_ID"].str.isnumeric()

0      False
1      False
2      False
3      False
4      False
       ...  
609    False
610    False
611    False
612    False
613    False
Name: Loan_ID, Length: 614, dtype: bool

### 17. Handle Missing Values in Strings


Safely perform string operations even if null values exist.
- Pandas automatically ignores NaN values.

In [118]:
df["Gender"].str.lower()

0        male
1      female
2      female
3      female
4         NaN
        ...  
609      male
610      male
611       NaN
612      male
613      male
Name: Gender, Length: 614, dtype: object

### 18. Convert Column to String (astype)

Converts column to string data type.

In [119]:
df["Loan_Amount_Term"].astype(str)

0      360.0
1      360.0
2      180.0
3      480.0
4      360.0
       ...  
609    360.0
610    180.0
611    300.0
612    180.0
613    360.0
Name: Loan_Amount_Term, Length: 614, dtype: object

### 19. Count Occurrences of Strings

Counts unique values in a column.

In [120]:
df["Property_Area"].value_counts()

Property_Area
Semiurban    233
Urban        202
Rural        179
Name: count, dtype: int64

# (10) DATE & TIME MANIPULATION IN PANDAS

#### DateTime represents date and time together (year, month, day, hour, minute, second).
- DateTime manipulation in Pandas is used to convert, analyze, extract, and perform calculations on date and time data.

### 1) Convert Column to DateTime (to_datetime)
Converts a column into DateTime format.

In [123]:
import pandas as pd

df = pd.DataFrame({"Loan_Date": ["2024-01-10"]})
df["Loan_Date"] = pd.to_datetime(df["Loan_Date"])
print(df)

   Loan_Date
0 2024-01-10


### 2) Extract Year


Extracts year from date.

In [124]:
import pandas as pd

df = pd.DataFrame({"Loan_Date": ["2024-01-10"]})
df["Loan_Date"] = pd.to_datetime(df["Loan_Date"])
print(df["Loan_Date"].dt.year)

0    2024
Name: Loan_Date, dtype: int32


### 3) Extract Month

In [125]:
import pandas as pd

df = pd.DataFrame({"Loan_Date": ["2024-01-10"]})
df["Loan_Date"] = pd.to_datetime(df["Loan_Date"])
print(df["Loan_Date"].dt.month)

0    1
Name: Loan_Date, dtype: int32


### 4) Extract Day

In [126]:
import pandas as pd

df = pd.DataFrame({"Loan_Date": ["2024-01-10"]})
df["Loan_Date"] = pd.to_datetime(df["Loan_Date"])
print(df["Loan_Date"].dt.day)

0    10
Name: Loan_Date, dtype: int32


### 5) Extract Day Name

In [127]:
import pandas as pd

df = pd.DataFrame({"Loan_Date": ["2024-01-10"]})
df["Loan_Date"] = pd.to_datetime(df["Loan_Date"])
print(df["Loan_Date"].dt.day_name())

0    Wednesday
Name: Loan_Date, dtype: object


### 6) Extract Month Name

In [128]:
import pandas as pd

df = pd.DataFrame({"Loan_Date": ["2024-01-10"]})
df["Loan_Date"] = pd.to_datetime(df["Loan_Date"])
print(df["Loan_Date"].dt.month_name())

0    January
Name: Loan_Date, dtype: object


### 7) Extract Weekday Number

In [129]:
import pandas as pd

df = pd.DataFrame({"Loan_Date": ["2024-01-10"]})
df["Loan_Date"] = pd.to_datetime(df["Loan_Date"])
print(df["Loan_Date"].dt.weekday)

0    2
Name: Loan_Date, dtype: int32


### 8) Current Date & Time

In [130]:
import pandas as pd

print(pd.Timestamp.now())

2026-01-30 17:04:55.761877
