## 1. Create a NumPy array of shape (4, 5) with values from 0 to 19. Reshape it to (2, 10) and print its shape, size, and data type.


In [3]:
import numpy as np
arr = np.arange(20).reshape(4, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [4]:
reshaped_arr = arr.reshape(2, 10)
print(reshaped_arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [5]:
print(reshaped_arr.shape)

(2, 10)


In [6]:
print(reshaped_arr.size)

20


In [7]:
print(reshaped_arr.dtype)

int32


## 2. Create a 3D array of shape (2, 3, 4) filled with numbers from 1 to 24. Write code to get:
   - The second 2D matrix
   - The last element of each 2D matrix


In [8]:
import numpy as np

arr = np.arange(1, 25).reshape(2, 3, 4)
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


## 3. Create a 1D array with 12 elements and reshape it into a 3x4 array using reshape. Now change it to 4x3 using resize and observe the difference.


In [9]:
import numpy as np

arr = np.arange(1, 13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [10]:
arr_reshaped = arr.reshape(3, 4)
print(arr_reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
arr.resize(4, 3)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## 4. Given a 5x5 matrix, extract:
   - The third column
   - The last two rows


In [12]:
arr = np.arange(1, 26).reshape(5, 5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [13]:
third_col = arr[:, 2]
print(third_col)

[ 3  8 13 18 23]


## 5. Create an array a = np.array([10, 20, 30, 40, 50]). Extract elements at positions [1, 4, 2] using advanced indexing.


In [14]:
a = np.array([10, 20, 30, 40, 50])
print(a)

[10 20 30 40 50]


In [15]:
result = a[[1, 4, 2]]
print(result)

[20 50 30]


## 6. Create a 2D array of shape (6,6) and slice the elements from rows 2 to 5 and columns 1 to 4.


In [17]:
a = np.arange(1, 37).reshape(6, 6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [19]:
sliced = a[2:6, 1:5]
print(sliced)

[[14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]
 [32 33 34 35]]


## 7. Generate a 3x3 array using np.random.randn and find how many values are negative.

In [20]:
arr = np.random.randn(3, 3)
print(arr)

[[-0.02622028  0.37863061  0.50068156]
 [-0.36116805 -1.38968249 -0.22479798]
 [ 0.18686291  0.48407388 -1.48665509]]


In [21]:
negc = np.sum(arr<0)
print(negc)

5


## 8. Create a 4x4 array using np.random.rand and multiply all values by 100. Find the maximum and its position.

In [22]:
arr = np.random.rand(4, 4)
print(arr)

[[0.43482892 0.19284195 0.36597148 0.10606471]
 [0.41043923 0.14802548 0.99774242 0.29018768]
 [0.8702508  0.0329962  0.52301113 0.49643261]
 [0.24382416 0.53192488 0.56610794 0.77765553]]


In [23]:
mul = arr * 100
print(mul)

[[43.48289218 19.28419492 36.59714843 10.60647056]
 [41.04392349 14.80254758 99.77424154 29.01876842]
 [87.02507986  3.29961981 52.30111266 49.64326101]
 [24.38241605 53.19248845 56.61079359 77.76555274]]


In [26]:
max1= mul.max()
print(max1)

99.77424153925377


In [27]:
pos = np.unravel_index(mul.argmax(), mul.shape)
print("Position of max:", pos)

Position of max: (1, 2)


## 9. Create an array of shape (3, 5) with random integers between 10 and 50 using randint. Replace all even numbers with -1.

In [29]:
arr = np.random.randint(10, 51, size=(3, 5))
print(arr)

[[16 26 45 14 28]
 [22 41 24 34 36]
 [37 43 21 31 21]]


In [30]:
arr[arr % 2==0] = -1
print(arr)

[[-1 -1 45 -1 -1]
 [-1 41 -1 -1 -1]
 [37 43 21 31 21]]


In [32]:
for i in range(arr.shape[0]):      # rows
    for j in range(arr.shape[1]):  # columns
        if arr[i, j] % 2 == 0:
            arr[i, j] = -1
print(arr)

[[-1 -1 45 -1 -1]
 [-1 41 -1 -1 -1]
 [37 43 21 31 21]]


## 10. Use np.random.choice to randomly select 5 elements from [1, 2, 3, 4, 5, 6, 7] with replacement. Count how many times 3 occurs.

In [36]:
arr = np.random.choice([1, 2, 3, 4, 5, 6, 7], size=5, replace = True)
print(arr)

[2 1 2 6 1]


In [38]:
coun = np.count_nonzero(arr==3)
print(coun)

0


## 11. Create a 5x5 identity matrix using np.eye. Change the diagonal values to 5

In [39]:
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [41]:
np.fill_diagonal(arr, 5)
print(arr)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


## 12. Create a 3x3 matrix filled with 7 using np.full and change its center value to 0.

In [43]:
arr = np.full((3, 3), 7)
print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [44]:
arr[1, 1]=0
print(arr)

[[7 7 7]
 [7 0 7]
 [7 7 7]]


## 13. Use np.linspace to create 50 values between 1 and 10. Find the difference between each consecutive value.

In [45]:
arr = np.linspace(1, 10, 50)
print("Array:\n", arr)

Array:
 [ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [46]:
diff = np.diff(arr)
print("\nDifferences:\n", diff)


Differences:
 [0.18367347 0.18367347 0.18367347 0.18367347 0.18367347 0.18367347
 0.18367347 0.18367347 0.18367347 0.18367347 0.18367347 0.18367347
 0.18367347 0.18367347 0.18367347 0.18367347 0.18367347 0.18367347
 0.18367347 0.18367347 0.18367347 0.18367347 0.18367347 0.18367347
 0.18367347 0.18367347 0.18367347 0.18367347 0.18367347 0.18367347
 0.18367347 0.18367347 0.18367347 0.18367347 0.18367347 0.18367347
 0.18367347 0.18367347 0.18367347 0.18367347 0.18367347 0.18367347
 0.18367347 0.18367347 0.18367347 0.18367347 0.18367347 0.18367347
 0.18367347]


## 14. Create an array using np.logspace(1, 3, 5) and round off the values to 2 decimal places.

In [47]:
arr = np.logspace(1, 3, 5)  
print("Original array:\n", arr)

Original array:
 [  10.           31.6227766   100.          316.22776602 1000.        ]


In [48]:
rounded_arr = np.round(arr, 2)
print("\nRounded array:\n", rounded_arr)


Rounded array:
 [  10.     31.62  100.    316.23 1000.  ]


## 15. Create a 2x3 array and subtract a 1D array of shape (3,) from it. Explain the broadcasting rule applied.


In [49]:
arr2d = np.array([[5, 10, 15],
                  [20, 25, 30]])
print(arr2d)

[[ 5 10 15]
 [20 25 30]]


In [50]:
arr1d = np.array([1, 2, 3])
print(arr1d)

[1 2 3]


In [51]:
result = arr2d - arr1d
print("\nResult:\n", result)


Result:
 [[ 4  8 12]
 [19 23 27]]


## 16. Create a 3x3 array and apply the following operations element-wise: square, log, exponential, and sine.


In [52]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Original Array:\n", arr)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
sq = np.square(arr)
print("\nSquare:\n", sq)

log_arr = np.log(arr)
print("\nLog:\n", log_arr)

exp_arr = np.exp(arr)
print("\nExponential:\n", exp_arr)

sin_arr = np.sin(arr)
print("\nSine:\n", sin_arr)


Square:
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]

Log:
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]

Exponential:
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Sine:
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


## 17) 17. Create a 4x4 matrix with random integers between 1 and 100. Normalize the matrix using broadcasting.


In [56]:
arr = np.random.randint(1, 101, size = (4, 4))
print(arr)

[[94 71 54 16]
 [27 19 67 50]
 [69 43  9 21]
 [ 9 43 28  4]]


In [57]:
norm_arr = (arr - arr.min()) / (arr.max() - arr.min())
print("\nNormalized Matrix:\n", norm_arr)


Normalized Matrix:
 [[1.         0.74444444 0.55555556 0.13333333]
 [0.25555556 0.16666667 0.7        0.51111111]
 [0.72222222 0.43333333 0.05555556 0.18888889]
 [0.05555556 0.43333333 0.26666667 0.        ]]


## 18. Create an array of 5 angles in degrees. Convert to radians and calculate sin and cos using np.pi.


In [58]:
angles_deg = np.array([0, 30, 45, 60, 90])

# Convert degrees to radians using np.pi
angles_rad = angles_deg * (np.pi / 180)

# Calculate sine and cosine of each angle in radians
sin_values = np.sin(angles_rad)
cos_values = np.cos(angles_rad)

print("Angles in degrees:", angles_deg)
print("Angles in radians:", angles_rad)
print("Sine values:", sin_values)
print("Cosine values:", cos_values)

Angles in degrees: [ 0 30 45 60 90]
Angles in radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine values: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine values: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


## 19) 19. Given an array with float values, convert it to integer using astype and calculate the sum before and after conversion.


In [59]:
float_array = np.array([1.5, 2.7, 3.9, 4.2, 5.8])

# Calculate sum before conversion
sum_before = np.sum(float_array)

# Convert to integer using astype
int_array = float_array.astype(int)

# Calculate sum after conversion
sum_after = np.sum(int_array)

print("Original float array:", float_array)
print("Sum before conversion:", sum_before)
print("Converted integer array:", int_array)
print("Sum after conversion:", sum_after)

Original float array: [1.5 2.7 3.9 4.2 5.8]
Sum before conversion: 18.1
Converted integer array: [1 2 3 4 5]
Sum after conversion: 15


## 20) Create a mixed array (strings + numbers) and convert the numeric strings to actual numbers using astype.


In [60]:
arr = np.array(['10', '20', '30', 'forty', '50'])
is_numeric = [x.isdigit() for x in arr]
converted = np.array([int(x) if x.isdigit() else x for x in arr])
print(converted)

['10' '20' '30' 'forty' '50']


## 21) Generate a 1D array with 15 random integers from 0 to 100. Replace all values divisible by 5 with -99.


In [61]:
arr = np.random.randint(0, 101, size=15)
print("Original array:", arr)
arr[arr % 5 == 0] = -99
print("Modified array:", arr)

Original array: [50 61 83 37 19  1 46 76 15 99 18 89 67 23 28]
Modified array: [-99  61  83  37  19   1  46  76 -99  99  18  89  67  23  28]


## 22) Given a 2D array, write code to set all values greater than 50 to 100.

In [62]:
arr = np.array([[10, 55, 30],
                [60, 45, 80],
                [25, 90, 50]])

print("Original array:\n", arr)
arr[arr > 50] = 100
print("Modified array:\n", arr)

Original array:
 [[10 55 30]
 [60 45 80]
 [25 90 50]]
Modified array:
 [[ 10 100  30]
 [100  45 100]
 [ 25 100  50]]


## 23) Create an array of 20 elements using randint(1, 100, 20). Filter out only even numbers and sort them.


In [63]:
arr = np.random.randint(1, 101, 20)
print("Original array:", arr)
even_numbers = arr[arr % 2 == 0]
sorted_even = np.sort(even_numbers)
print("Sorted even numbers:", sorted_even)

Original array: [44 30 34 45  9 68  9 39 31  6 56 65 49 97 41 30 72 67  5 93]
Sorted even numbers: [ 6 30 30 34 44 56 68 72]


## 24) Create a 4x4 array and use np.where to replace all elements < 10 with 0 and others with 1.


In [64]:
arr = np.random.randint(0, 21, (4, 4))
print("Original array:\n", arr)

result = np.where(arr < 10, 0, 1)
print("Modified array:\n", result)

Original array:
 [[ 5  9 20 18]
 [ 7 15  0 13]
 [ 5 20 15 12]
 [ 3  9 13 20]]
Modified array:
 [[0 0 1 1]
 [0 1 0 1]
 [0 1 1 1]
 [0 0 1 1]]


## 25. Use np.where to find positions of all elements divisible by 3 in a randomly generated 5x5 matrix.


In [65]:
matrix = np.random.randint(1, 51, (5, 5))
print("Matrix:\n", matrix)

# Find positions where elements are divisible by 3
positions = np.where(matrix % 3 == 0)

print("Positions (row, column) of elements divisible by 3:")
for i in range(len(positions[0])):
    print(f"({positions[0][i]}, {positions[1][i]})")

Matrix:
 [[36 28  1 35 18]
 [48 49 30 32 10]
 [ 4 39 25 38 22]
 [34 35 16  9 35]
 [24 15 25 22  5]]
Positions (row, column) of elements divisible by 3:
(0, 0)
(0, 4)
(1, 0)
(1, 2)
(2, 1)
(3, 3)
(4, 0)
(4, 1)


## 26. Create a 2D array of shape (6,4). Find:
   - Mean of each column
   - Std deviation of the entire array
   - Median of each row


In [66]:
arr_6x4 = np.random.randint(0, 100, (6,4))
mean_cols = np.mean(arr_6x4, axis=0)
std_all = np.std(arr_6x4)
median_rows = np.median(arr_6x4, axis=1)

print(mean_cols)
print(std_all)
print(median_rows)

[49.5        48.         50.16666667 59.83333333]
27.627450871672302
[61.  82.5 25.5 52.5 34.  65. ]


## 27. Generate a random array of 1000 values using randn. Count how many values fall between -1 and 1 (hint: normal distribution rule).


In [67]:
arr_1000 = np.random.randn(1000)
count_between = np.sum((arr_1000 > -1) & (arr_1000 < 1))
print(count_between)

696


## 28) Create a 5x5 array and calculate row-wise and column-wise sum and mean.

In [68]:
arr_5x5 = np.random.randint(0, 100, (5,5))
row_sum = np.sum(arr_5x5, axis=1)
col_sum = np.sum(arr_5x5, axis=0)
row_mean = np.mean(arr_5x5, axis=1)
col_mean = np.mean(arr_5x5, axis=0)

print(row_sum)
print(col_sum)
print(row_mean)
print(col_mean)

[219 245 259 317 247]
[347 162 254 313 211]
[43.8 49.  51.8 63.4 49.4]
[69.4 32.4 50.8 62.6 42.2]
